language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y automake
  - sudo apt-get install -y libtool

script:
  - make submodule
  - make depend
  - make
